[package]
name = "Cosmos-on-the-rocks"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_asset_loader = "0.23.0"
bevy_enhanced_input = "0.12.0"
bevy_seedling = "0.4.0"
bevy_yarnspinner = "0.5.0"
bevy_yarnspinner_example_dialogue_view = "0.5.0"
